Fixed Exploit and Possible Bypass
esx-framework/esx_drugs pull request #21
Opened 2023-08-25 16:09 UTC by RH-Adv1c3

- SellDrug minus was not checked if the amount is minus or not, which **could** cause issues in some builds
- Added Pickup Distance Check 90 distance from config position based upon the weed spawn field

2023-08-25 16:10 UTC, RH-Adv1c3 commented
Just noticed a small typo on my side, line 112 the src variable needs to be source instead.

2023-08-25 16:41 UTC, Gellipapa requested changes
Please read my comments and fix problems.

2023-08-25 16:41 UTC, Gellipapa commented on server/main.lua
> +	if amount < 0 then
If amount < 0  you should return. Ohh and 0 can sell?

2023-08-25 16:41 UTC, Gellipapa commented on server/main.lua
> +		if ValidateProcessCannabis(src) then
yes please fix this typo src to source

2023-08-25 16:41 UTC, Gellipapa commented on server/main.lua
> +local function BanPlayer(src,reason)
Rename method name, this is kick player, no ban player.

2023-08-25 17:07 UTC, RH-Adv1c3 commented
Good catch, still sleeping half haha

2023-08-25 17:17 UTC, Gellipapa approved these changes
It's okey, did you test this?

2023-08-25 17:32 UTC, RH-Adv1c3 commented
> It's okey, did you test this?

No otherwise I would've found the typo and the variable name mismatch. 
I run a custom framework so I can't test it really easy

2023-08-25 17:40 UTC, Gellipapa commented
It's okey , we need test this.

2023-08-25 17:41 UTC, RH-Adv1c3 commented
> It's okey , we need test this.

No problem, I found the script and thought I'd suggest some changes for more security.
You can see on my Profile that it's something I do more often

2023-08-27 11:20 UTC, Gellipapa commented
@RH-Adv1c3 Hi! I was tested this pr, and it works but -1 you can't add input field, because Config you can add min and max value and if you write minus number in input, context menu return 1 all time and your print never show. One or two things still work interestingly but they are not your changes, we'll fix or rewrite the whole thing later.

2023-08-27 11:20 UTC, merged

2023-08-27 11:23 UTC, RH-Adv1c3 commented
> @RH-Adv1c3 Hi! I was tested this pr, and it works but -1 you can't add input field, because Config you can add min and max value and if you write minus number in input, context menu return 1 all time and your print never show. One or two things still work interestingly but they are not your changes, we'll fix or rewrite the whole thing later.

People can still trigger the server event directly with a mod menu, so anything that is not double checked in the server code is still possibly even though your client menu's are solid proof

2023-08-27 11:25 UTC, Gellipapa commented
> > @RH-Adv1c3 Hi! I was tested this pr, and it works but -1 you can't add input field, because Config you can add min and max value and if you write minus number in input, context menu return 1 all time and your print never show. One or two things still work interestingly but they are not your changes, we'll fix or rewrite the whole thing later.
> 
> People can still trigger the server event directly with a mod menu, so anything that is not double checked in the server code is still possibly even though your client menu's are solid proof

Yes, that's why I accepted it because it's safe. Good job.

2023-08-27 11:28 UTC, RH-Adv1c3 commented
> > > @RH-Adv1c3 Hi! I was tested this pr, and it works but -1 you can't add input field, because Config you can add min and max value and if you write minus number in input, context menu return 1 all time and your print never show. One or two things still work interestingly but they are not your changes, we'll fix or rewrite the whole thing later.
> 
> > 
> 
> > People can still trigger the server event directly with a mod menu, so anything that is not double checked in the server code is still possibly even though your client menu's are solid proof
> 
> 
> 
> Yes, that's why I accepted it because it's safe. Good job.

I'll look further at it later today, because I know there is still one more minimal possible method to bypass the checks. So you'll get a new pull request today haha